---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  tasks:
  - name: Check if Service Exists
    stat: path=/etc/init.d/httpd
    register: service_status
   
  - name: Check for the existence of httpd
    debug:
      msg: Httpd installed!
    when: service_status.stat.exists
   
  - name: Fail if httpd does not exist
    fail:
      msg: You do not have httpd installed!
    when: service_status.stat.exists == false

